// @generated by `cargo run -p xtask -- generate-api-types`. Do not edit.
//! Enrollment wire types, generated from `api/enrollment-v1alpha1.yaml`.
//!
//! Regenerate with `cargo run -p xtask -- generate-api-types`. The format
//! decisions live in `xtask/src/api_codegen.rs`.

#![allow(
    missing_docs,
    unused_qualifications,
    reason = "typify-generated wire types are not hand-maintained"
)]

///The certificate issued to a site, returned inline from enroll.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
pub struct Enrollment {
    /**The grid CA certificate, PEM encoded. Returned with the leaf so a
site holds the trust anchor without a separate fetch.
*/
    #[serde(rename = "caCertificate")]
    pub ca_certificate: ::std::string::String,
    ///The issued certificate, PEM encoded.
    pub certificate: ::std::string::String,
    /**The issued-enrollment row identifier. Additive: a future retrieval or
idempotent-replay lookup can key on it.
*/
    pub id: ::uuid::Uuid,
    /**Lowercase hex SHA-256 over the request's public key.
*/
    #[serde(rename = "publicKeySha256")]
    pub public_key_sha256: ::std::string::String,
    /**The name the grid assigned, carried as a URI SAN on the certificate.
*/
    #[serde(rename = "spiffeId")]
    pub spiffe_id: ::std::string::String,
}
/**What a site submits to enroll: a certificate signing request and nothing
else. The token pins the name, so a submission cannot assert one.
*/
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
pub struct EnrollmentRequest {
    /**PKCS#10 certificate signing request, PEM encoded. The private key
stays with the requester and is never sent.
*/
    pub csr: ::std::string::String,
}
/**The token a grid-admin hands to a site. Returned once, at mint; only its
digest is stored after that.
*/
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
pub struct EnrollmentToken {
    ///When the token stops being usable.
    #[serde(rename = "expiresAt")]
    pub expires_at: ::std::string::String,
    ///The name the token pins.
    #[serde(rename = "siteName")]
    pub site_name: ::std::string::String,
    ///The one-time token, presented once at enroll.
    pub token: ::std::string::String,
    ///Identifier, for revoking the token before it is redeemed.
    #[serde(rename = "tokenId")]
    pub token_id: ::uuid::Uuid,
}
///What a grid-admin submits to mint a token.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
pub struct EnrollmentTokenRequest {
    /**How long the token stays usable, in seconds. A default applies when
unset. An explicit value must be greater than zero and at most
604800 (seven days).
*/
    #[serde(
        rename = "expiresInSecs",
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub expires_in_secs: ::std::option::Option<i64>,
    ///The grid the site joins.
    #[serde(rename = "gridNetworkRef")]
    pub grid_network_ref: ::std::string::String,
    /**The name the token pins. The grid-admin chooses it, so the site
never names itself.
*/
    #[serde(rename = "siteName")]
    pub site_name: ::std::string::String,
}
///A failure, described so a caller can act on it.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Eq, PartialEq)]
pub struct Error {
    ///Machine-readable code.
    pub error: ::std::string::String,
    ///What went wrong, and what would fix it.
    pub message: ::std::string::String,
}
/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
