//! Generate the enrollment wire types from the `OpenAPI` spec.
//!
//! The spec `api/enrollment-v1alpha1.yaml` is the source of truth. This reads
//! its `components/schemas`, hands them to typify, and writes Rust types to
//! `enrollment/src/generated.rs`. `CI` regenerates and fails on any diff, so the
//! types cannot drift from the spec.
//!
//! Two format decisions shape the output:
//!   - `format: uuid` becomes `uuid::Uuid`, matching the store and the router `Path<Uuid>`.
//!   - `format: date-time` is dropped before generation so timestamps become `String`. typify maps date-time to
//!     `chrono::DateTime`, but enrollment uses the `time` crate with an explicit rfc3339 serde adapter that typify will
//!     not reproduce. Keeping the wire field a `String` preserves the rfc3339 contract, and the handler parses it to
//!     `time::OffsetDateTime`.

use schemars::Schema;
use schemars08::schema::Schema as TypifySchema;
use typify::{TypeSpace, TypeSpaceSettings};

/// Spec read, relative to the workspace root.
const SPEC: &str = "api/enrollment-v1alpha1.yaml";
/// Generated output, relative to the workspace root.
const OUT: &str = "enrollment/src/generated.rs";

/// Read the spec, generate the wire types, and write them to [`OUT`].
///
/// # Errors
///
/// Fails if the spec is missing or malformed, if a schema cannot be converted,
/// or if the output cannot be written.
pub(crate) fn generate() -> Result<(), Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string(SPEC).map_err(|e| format!("reading {SPEC}: {e}"))?;
    let mut doc: serde_json::Value = serde_yaml::from_str(&text)?;

    let schemas = doc
        .get_mut("components")
        .and_then(|c| c.get_mut("schemas"))
        .and_then(serde_json::Value::as_object_mut)
        .ok_or("spec has no components.schemas")?;

    let mut defs: Vec<(String, TypifySchema)> = Vec::with_capacity(schemas.len());
    for (name, raw) in schemas.iter() {
        let mut value = raw.clone();
        normalize(&mut value);
        let schema: Schema = serde_json::from_value(value)?;
        // Typify 0.8 still consumes schemars 0.8 schemas; keep that boundary explicit while parsing with schemars 1.x.
        let typify_schema = serde_json::from_value(serde_json::to_value(schema)?)?;
        defs.push((name.clone(), typify_schema));
    }
    defs.sort_by(|a, b| a.0.cmp(&b.0));

    let mut settings = TypeSpaceSettings::default();
    settings
        .with_struct_builder(false)
        .with_derive("PartialEq".to_owned())
        .with_derive("Eq".to_owned());
    let mut space = TypeSpace::new(&settings);
    space.add_ref_types(defs)?;

    let ast = syn::parse2(space.to_stream())?;
    let body = prettyplease::unparse(&ast);
    std::fs::write(OUT, format!("{HEADER}{body}"))?;
    println!("generated {OUT}");
    Ok(())
}

/// Header prepended to the generated file.
///
/// The `@generated` marker on the first line makes rustfmt skip the file, which
/// its `format_generated_files = false` setting keys on, so prettyplease output
/// is not reformatted out from under the drift check.
const HEADER: &str = "\
// @generated by `cargo run -p xtask -- generate-api-types`. Do not edit.
//! Enrollment wire types, generated from `api/enrollment-v1alpha1.yaml`.
//!
//! Regenerate with `cargo run -p xtask -- generate-api-types`. The format
//! decisions live in `xtask/src/api_codegen.rs`.

#![allow(
    missing_docs,
    unused_qualifications,
    reason = \"typify-generated wire types are not hand-maintained\"
)]

";

/// Rewrite `OpenAPI` 3.1 schema constructs into what typify (schemars 0.8) reads.
///
/// typify resolves `$ref` as `#/definitions/<name>`, not the `OpenAPI`
/// `#/components/schemas/<name>`, maps `format: date-time` to chrono, and does
/// not model the 3.1 `examples`. String and numeric constraints are dropped so
/// constrained fields keep plain types rather than validated newtypes (regress,
/// `NonZeroU64`). Validation stays in the handler, as in model.rs.
fn normalize(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Object(map) => {
            if let Some(serde_json::Value::String(reference)) = map.get_mut("$ref")
                && let Some(rest) = reference.strip_prefix("#/components/schemas/")
            {
                *reference = format!("#/definitions/{rest}");
            }
            if map.get("format").and_then(serde_json::Value::as_str) == Some("date-time") {
                map.remove("format");
            }
            for key in ["pattern", "minLength", "maxLength", "minimum", "maximum", "examples"] {
                map.remove(key);
            }
            for child in map.values_mut() {
                normalize(child);
            }
        },
        serde_json::Value::Array(items) => {
            for item in items {
                normalize(item);
            }
        },
        serde_json::Value::Null
        | serde_json::Value::Bool(_)
        | serde_json::Value::Number(_)
        | serde_json::Value::String(_) => {},
    }
}

/// Regenerate and report whether the checked-in file is stale, for CI.
///
/// # Errors
///
/// Fails if generation fails or the output cannot be compared.
pub(crate) fn check() -> Result<(), Box<dyn std::error::Error>> {
    let before = std::fs::read_to_string(OUT).unwrap_or_default();
    generate()?;
    let after = std::fs::read_to_string(OUT)?;
    if before != after {
        return Err(format!("{OUT} is stale, run `cargo run -p xtask -- generate-api-types` and commit").into());
    }
    Ok(())
}
